name = "pdf-form-engine"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

# Uncomment to use R2 for PDF storage
# [[r2_buckets]]
# binding = "PDF_BUCKET"
# bucket_name = "pdf-outputs"